name: Issues and PR Workflow

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add labels to issues
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            - enhancement
            - bug
            - high-priority
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run code formatting check
        run: npm run format-check

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

  notify-maintainers:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'high-priority')
    steps:
      - name: Notify maintainers for high-priority issues
        run: |
          echo "@maintainers Please review the new high-priority issue: ${{ github.event.issue.html_url }}"